Remove </noscript>-tags that break Firefox CSS loading
eddiewebb/hugo-resume pull request #56
Opened 2020-02-13 17:24 UTC by seandlg

Since `preload` files still don't seem to work in Firefox, `noscript`-tags must be removed to make Firefox download css files. See [this SO-link](https://stackoverflow.com/questions/45321043/preload-css-file-not-supported-on-firefox-and-safari-mac "SO-link") for the `preload`-issue, [this SO-link](https://stackoverflow.com/questions/218162/embedding-extra-styles-with-noscript "SO-link") for the `</noscript>`-issue.

2020-10-20 02:35 UTC, awhitford commented
The `<noscript>` tag is only valid inside `<body>`, so having it under `<head>` is _illegal_.  I'd like to see those removed too.

2020-10-20 22:26 UTC, eddiewebb requested changes
Shouldn't this also remove the duplicate preload then? Is this still an issue with Firefox?  @awhitford - any of your recent change flurry impact this?

2020-10-21 04:57 UTC, awhitford commented
I did not do any testing with Firefox; I am not fully aware of this issue and have no reason to believe that my recent changes have adequately addressed this issue.

2023-06-13 13:21 UTC, eddiewebb commented
I am closing this because it's stale at this point and looks like preload is widely supported now - https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/rel/preload

2023-06-13 13:21 UTC, closed without merging